"""Constants for Chromacore registry module types."""

MODULE_TYPE_SCHEME_GENERATOR = "scheme_generator"
MODULE_TYPE_ANIMATION_SEQUENCE = "animation_sequence"
MODULE_TYPE_RENDERER = "renderer"
MODULE_TYPE_COLOUR_SPACE = "colour_space"
MODULE_TYPE_EMITTER = "emitter"
MODULE_TYPE_UTILITY = "utility"

ALL_MODULE_TYPES = {
    MODULE_TYPE_SCHEME_GENERATOR,
    MODULE_TYPE_ANIMATION_SEQUENCE,
    MODULE_TYPE_RENDERER,
    MODULE_TYPE_COLOUR_SPACE,
    MODULE_TYPE_EMITTER,
    MODULE_TYPE_UTILITY,
}
